#!/bin/bash

URI="radio://0/$1/2M/E7E7E7E7$2"

echo "URI: $URI"
echo "Flashing main firmware..."
python -m cfloader -w $URI flash crazyflie-firmware/cf2.bin stm32-fw
echo "Main firmware flashed, sleeping for 1 second...\n\n"
sleep 1

echo "Flashing NRF51 firmware..."
python -m cfloader -w $URI flash crazyflie2-nrf-firmware/cf2_nrf-2021.03.bin nrf51-fw
echo "Done!"