#!/bin/bash


pyinstaller \
    --name "Swarm Controller" \
    --icon ./application/resources/images/icon_black.ico \
    --window \
    --noconfirm \
    cli.py



# pyinstaller  --onefile --name "Swarm Controller" --icon ./application/resources/images/icon_black.ico --paths "C:\Users\Michael\AppData\Local\Programs\Python\Python39\Lib\site-packages" ./application