#!/bin/bash


winPy=C:/Users/Michael/AppData/Local/Programs/Python/Python39/python.exe
pyqt5ac --config ./application/config.yml

# clear && $winPy ./prototyping/goto-test.py 
clear && $winPy ./cli.py
# clear && $winPy ./application/__main__.py -platform windows:dpiawareness=0
 