#!/bin/bash


winPy=C:/Users/Michael/AppData/Local/Programs/Python/Python39/python.exe
winPip=C:/Users/Michael/AppData/Local/Programs/Python/Python39/Scripts/pip.exe

$winPy -m pip install --upgrade pip wheel setuptools virtualenv
virtualenv venv
source ./venv/bin/activate
$winPip install cflib
$winPip install keyboard
$winPip install openvr
$winPip install numpy
$winPy -m pip install docutils pygments pypiwin32 PyQt5
$winPy -m pip install pyqt5ac
$winPy -m pip install vispy